version: '3.9'

services:
  next-app:
    container_name: honghao
    image: okhubvn/honghao:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        NEXT_PUBLIC_API: ${NEXT_PUBLIC_API}
        NEXT_PUBLIC_API_ACF: ${NEXT_PUBLIC_API_ACF}
        OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
        NEXT_PUBLIC_SECRET_KEY_HASH: ${NEXT_PUBLIC_SECRET_KEY_HASH}
        NEXT_PUBLIC_ONEPAY_HOST: ${NEXT_PUBLIC_ONEPAY_HOST}
        NEXT_PUBLIC_ACCESS_CODE: ${NEXT_PUBLIC_ACCESS_CODE}
        NEXT_PUBLIC_MERCHANT_ID: ${NEXT_PUBLIC_MERCHANT_ID}
        NEXT_PUBLIC_REQUEST: ${NEXT_PUBLIC_REQUEST}

    restart: always
    ports:
      - 3000:3000
    networks:
      - honghaonetwork

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  honghaonetwork:
    external: true
