import {Londrina_Solid} from 'next/font/google'
import './globals.css'
import Footer from '@/layouts/footer'
import Header from '@/layouts/header'
import localFont from 'next/font/local'
import ResponsiveProvider from '@/components/provider/responsiveProivder'

const londrina = Londrina_Solid({
  display: 'swap',
  weight: ['100', '300', '400', '900'],
  variable: '--font-londrina-solid',
  subsets: ['latin'],
})

const tripsans = localFont({
  src: [
    {
      path: './font/trip-sans.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './font/trip-sans-medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './font/trip-sans-bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './font/trip-sans-ultra.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-trip-sans',
  display: 'swap',
})

export const metadata = {
  title: 'Hong Ha Travel',
  description: 'Generated by create Dev Okhub',
}
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}
export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='canonical'
          href={process.env.DOMAIN}
        />
      </head>
      <body
        className={`${tripsans.className} ${tripsans.variable} ${londrina.variable}`}
        suppressHydrationWarning={true}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
